# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b111c053300c79887256ccdd4d8dfe9de9ccd143b47228472a396c4cabfe898cdadf211fc48c9e2f6a2ee4a1e03769c287b416f4e4458eb631278924b21a6fd

test:
  secret_key_base: ed5136b4d19142c749944433de7d5ea2f2235cc9819f957ac54d330258ace0d758625a2af8434c4f9c37a22bcb7cb6a937d744519fd18d5c504c83d6f2a54701

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
